"""sprint 3 documents

Revision ID: b9e5ec480815
Revises: cc40852cf63f
Create Date: 2026-08-30 19:18:07.240994

Autogenerated, then adjusted in two places.

* The enum types are declared once at module level and dropped explicitly in
  ``downgrade``. ``op.drop_table`` leaves a PostgreSQL enum type behind, so an
  un-adjusted downgrade would make the *next* upgrade fail on a type that already
  exists — a migration that is not reversible is a migration that cannot be tested.
* The enums store their values ("needs_review"), not their member names
  ("NEEDS_REVIEW"), matching what the API returns and what FR-UPL-005 names.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9e5ec480815"
down_revision: str | Sequence[str] | None = "cc40852cf63f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

document_type = sa.Enum("unclassified", name="document_type")
document_status = sa.Enum(
    "queued",
    "processing",
    "ready",
    "needs_review",
    "failed",
    name="document_status",
)


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("document_type", document_type, nullable=False),
        sa.Column("status", document_status, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_documents_storage_key_unique", "documents", ["storage_key"], unique=True)
    op.create_index(
        "ix_documents_user_id_checksum_unique",
        "documents",
        ["user_id", "checksum_sha256"],
        unique=True,
    )
    op.create_index(
        "ix_documents_user_id_created_at", "documents", ["user_id", "created_at"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_documents_user_id_created_at", table_name="documents")
    op.drop_index("ix_documents_user_id_checksum_unique", table_name="documents")
    op.drop_index("ix_documents_storage_key_unique", table_name="documents")
    op.drop_table("documents")
    document_status.drop(op.get_bind(), checkfirst=True)
    document_type.drop(op.get_bind(), checkfirst=True)
